apiVersion: v1
kind: Service
metadata:
  name: docuseal
  namespace: docuseal
spec:
  type: NodePort
  ports:
    - name: "docusealwebui"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    docuseal: docuseal
